---
- name: Configure host.
  hosts: all

  roles:
    - role: elliotweiser.osx-command-line-tools
    - role: ctorgalson.macos-hostname

  tasks:
    - import_tasks: tasks/touchid.yml
      tags: ['touchid']

    - import_tasks: tasks/wezterm.yml
      tags: ['app']

    - import_tasks: tasks/app.yml
      tags: ['app']

    - import_tasks: tasks/fish.yml
      tags: ['shell']

    - import_tasks: tasks/git.yml
      tags: ['git']
