---
- name: Setup brew cask fonts taps
  homebrew_tap:
    name: homebrew/cask-fonts

- name: Setup brew casks
  homebrew_cask:
    name:
    - github
    - 1password
    - bitwarden
    - chromium
    - jetbrains-toolbox
    - visual-studio-code
    - google-chrome
    - betterdisplay
    - moonlight
    - discord
    - snipaste
    - hiddenbar
    - teleport-connect
    - warp
    - bambu-studio
    state: present

- name: Setup brew font casks
  homebrew_cask:
    name:
    - font-caskaydia-cove-nerd-font
    - font-fira-code-nerd-font
    - font-menlo-for-powerline
    state: present

- name: Setup brew clis
  homebrew:
    name:
    - ansible
    - fish
    - gh
    - go
    - node
    - starship
    - neofetch
    - just
    - yubikey-agent
    - corepack
    - coreutils
    - diffutils
    - findutils
    - gawk
    - gnu-getopt
    - gnu-tar
    - grep
    - make
    - ncurses
    - pkg-config
    - wget
    - quilt
    - xz
    - gcc@11
    - buf
    - openjdk@17
    - ripgrep
    - eza
    - fd
    - sd
    - ykman
    - git-credential-oauth
    state: present

- name: Start yubikey agent
  ansible.builtin.command: brew services start yubikey-agent
  environment:
    PATH: "/opt/homebrew/bin:/usr/local/bin:{{ ansible_env.PATH }}"
  when: ansible_os_family == "Darwin"
  become: false
