version: '2'

services:
  mysql:
    container_name: mysql
    ports:
    - 3306:3306
    image: mariadb:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: IndexyzDevelopment

  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin/phpmyadmin
    ports:
    - 50001:80
    environment:
      PMA_HOST: mysql
    restart: always

  redis:
    container_name: redis
    image: redis:alpine
    ports:
    - 6379:6379
    environment:
      ALLOW_EMPTY_PASSWORD: 'yes'
    restart: always

  mongo:
    container_name: mongo
    ports:
    - 27017:27017
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    restart: always

  emqx:
    container_name: emqx
    ports:
    - 1883:1883
    - 8081:8081
    - 8083:8083
    - 8883:8883
    - 8084:8084
    - 18083:18083
    image: emqx/emqx
    restart: always

  postgres:
    container_name: postgres
    image: postgres:13.2-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: IndexyzDevelopment
    volumes:
    - ~/Dokcer/Postgres:/var/lib/postgresql/data
    ports:
    - 5432:5432
